services:
  api:
    build:
      context: ../..
      dockerfile: docker/sandbox/Dockerfile.sandbox
    container_name: sixbase-api-backoffice-${BRANCH_NAME:-default}
    env_file:
      - ../.env.sandbox
    command: yarn start
    ports:
      - "${PORT:-5000}:5000"
    environment:
      NODE_ENV: sandbox
      REDIS_HOST: sixbase-redis
      REDIS_PORT: ${REDIS_PORT:-6380}

networks:
  default:
    external: true
    name: sixbase-net